version: '3'

networks:
  gympoint:
    external: true

volumes:
  mysql-data:
  mongo-data:

services: 
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - gympoint
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/dumps/create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
    ports:
      - "3306:3306"
  mongo:
    image: mongo
    networks:
      - gympoint
    ports:
      - "27017:27017"
    volumes:
      - "mongo-data:/data/db"
  redis:
    image: redis:alpine
    networks:
      - gympoint
    ports:
      - "6379:6379"
  api:
    image: node:10
    working_dir: /home/node/app
    networks:
      - gympoint
    volumes:
      - ./api:/home/node/app
    ports:
      - "3333:3333"
    depends_on: 
      - mysql
      - mongo
      - redis
    command: bash -c "yarn && yarn start"
  web:
    image: node:10
    working_dir: /home/node/app
    networks:
      - gympoint
    volumes:
      - ./web:/home/node/app
    ports:
      - "3000:3000"
    depends_on: 
      - api
    command: bash -c "yarn && yarn start"